name: dolle-iot # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: IoT implementation at Dolle A/S # 79 char long summary
description: |
  For more information see README.md
icon: ./limcheck/src/gui/images/favicon.png
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  limcheck-gui:
    command: bin/desktop-launch $SNAP/opt/ros/snap/lib/limcheck/gui   
    common-id: limcheck-gui.desktop
    environment:
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
    
    plugs:
      - desktop-launch
      - home
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - network
      - network-bind 
      - camera
      - locale-control
    extensions: 
      - ros2-foxy

  limcheck-gather-data:
    command: opt/ros/foxy/bin/ros2 launch $SNAP/opt/ros/snap/share/limcheck/launch/gather_data.launch.py 
    common-id: limcheck-gather-data.desktop
    environment:
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
    plugs:
      - desktop-launch
      - home
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - wayland
      - x11
      - network
      - network-bind 
      - camera
      - locale-control
    extensions: 
      - ros2-foxy

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libgtk2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  ros-ws:
    plugin: colcon
    source: .
    override-pull: |
      snapcraftctl pull
      if [ ! -d "ros2_babel_fish" ] 
      then
      echo "Directories from github DOES NOT exists." 
      git clone --branch foxy https://github.com/LOEWE-emergenCity/ros2_babel_fish.git
      git clone https://github.com/StefanFabian/qml_ros2_plugin.git
      fi
    build-packages: 
      - make
      - gcc
      - g++
      - git
      - libblas-dev
      - libqt5-ukui-style-dev
      - libqt5charts5-dev
      - libqt5datavisualization5-dev
      - libqt5gamepad5-dev
      - libqt5gstreamer-dev
      - libqt5networkauth5-dev
      - libqt5opengl5-dev
      - libqt5pas-dev
      - libqt5remoteobjects5-dev
      - libqt5scxml5-dev
      - libqt5sensors5-dev
      - libqt5serialbus5-dev
      - libqt5serialport5-dev
      - libqt5svg5-dev
      - libqt5texttospeech5-dev
      - libqt5virtualkeyboard5-dev
      - libqt5waylandclient5-dev
      - libqt5waylandcompositor5-dev
      - libqt5webchannel5-dev
      - libqt5webkit5-dev
      - libqt5websockets5-dev
      - libqt5webview5-dev
      - libqt5x11extras5-dev
      - libqt5xdg-dev
      - libqt5xdgiconloader-dev
      - libqt5xmlpatterns5-dev
      - libqtav-dev
      - libqtav-private-dev
      - libqtdbusmock1-dev
      - libqtdbustest1-dev
      - libqtermwidget5-0-dev
      - libqtest-ocaml-dev
      - libqtspell-qt5-dev
      - qml-module-qtquick-controls2
      - qml-module-qtquick-controls
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-extras
      - qml-module-qtquick-layouts
      - qml-module-qtquick-localstorage
      - qml-module-qtquick-particles2
      - qml-module-qtquick-privatewidgets
      - qml-module-qtquick-scene2d
      - qml-module-qtquick-scene3d
      - qml-module-qtquick-shapes
      - qml-module-qtquick-templates2
      - qml-module-qtquick-virtualkeyboard
      - qml-module-qtquick-window2
      - qml-module-qtquick-xmllistmodel
      - qml-module-qtquick2
      - ros-foxy-rclcpp
      - ros-foxy-rcpputils
      - ros-foxy-rclcpp-action
      - ros-foxy-action-tutorials-interfaces
      - ros-foxy-image-transport
      - ros-foxy-tf2-ros
    stage-packages:  
      - ros-foxy-ros2run
      - ros-foxy-ros2launch
      - ros-foxy-rclcpp-action
      - ros-foxy-action-tutorials-interfaces
      - ros-foxy-image-transport
      - ros-foxy-tf2-ros
      - libdouble-conversion3
      - libpcre2-16-0
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5qml5
      - libqt5widgets5
      - libgio2.0-cil-dev
      - libgio3.0-cil-dev
      - qml-module-qtquick-controls2
      - qml-module-qtquick-controls
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-extras
      - qml-module-qtquick-layouts
      - qml-module-qtquick-localstorage
      - qml-module-qtquick-particles2
      - qml-module-qtquick-privatewidgets
      - qml-module-qtquick-scene2d
      - qml-module-qtquick-scene3d
      - qml-module-qtquick-shapes
      - qml-module-qtquick-templates2
      - qml-module-qtquick-virtualkeyboard
      - qml-module-qtquick-window2
      - qml-module-qtquick-xmllistmodel
      - qml-module-qtquick2
      - libblas-dev
